sudo: false
language: cpp
compiler:
  - clang

addons:
  apt:
    packages:
      - doxygen
      - libopenmpi-dev
      
cache:
  apt: true
  directories:
    - $HOME/installed
    
install:
  - |
    if [ ! -d "$HOME/installed/bin" ]; then
      set -e
      ### create a place to hold our local dependences
      mkdir -p $HOME/installed
      ### get a modern version of CMake
      wget --no-check-certificate -q http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz;
      tar xzf cmake-3.2.3-Linux-x86_64.tar.gz  -C $HOME/installed --strip-components=1
    else
      echo 'Using cached dependences.'
    fi
  
before_script:
  - export PATH="$HOME/installed/bin:$PATH"
  
script:
- bash build-doxygen.sh
- bash deploy-doxygen.sh
  