var annotated =
[
    [ "Grappa::AdjIterator< G >", "struct_grappa_1_1_adj_iterator.html", "struct_grappa_1_1_adj_iterator" ],
    [ "Aggregator", "class_aggregator.html", "class_aggregator" ],
    [ "AggregatorBuffer< max_size_ >", "class_aggregator_buffer.html", "class_aggregator_buffer" ],
    [ "AggregatorGenericCallHeader", "struct_aggregator_generic_call_header.html", "struct_aggregator_generic_call_header" ],
    [ "AggregatorMetrics", "class_aggregator_metrics.html", "class_aggregator_metrics" ],
    [ "Allocator", "class_allocator.html", "class_allocator" ],
    [ "AllocatorChunk", "struct_allocator_chunk.html", "struct_allocator_chunk" ],
    [ "AllReducer< T, ReduceOp >", "class_all_reducer.html", "class_all_reducer" ],
    [ "function_traits< ReturnType(ClassType::*)(Args...) const  >::arg< i >", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4_1_1arg.html", null ],
    [ "Grappa::BasicScheduler", "class_grappa_1_1_basic_scheduler.html", "class_grappa_1_1_basic_scheduler" ],
    [ "block_offset_t", "structblock__offset__t.html", "structblock__offset__t" ],
    [ "BufferVector< T >", "class_buffer_vector.html", "class_buffer_vector" ],
    [ "CacheAllocator< T >", "class_cache_allocator.html", "class_cache_allocator" ],
    [ "Cacheline", "struct_cacheline.html", "struct_cacheline" ],
    [ "CacheMetrics", "class_cache_metrics.html", "class_cache_metrics" ],
    [ "CacheRO< T, Allocator, Acquirer, Releaser >", "class_cache_r_o.html", "class_cache_r_o" ],
    [ "CacheRW< T, Allocator, Acquirer, Releaser >", "class_cache_r_w.html", "class_cache_r_w" ],
    [ "CacheWO< T, Allocator, Acquirer, Releaser >", "class_cache_w_o.html", "class_cache_w_o" ],
    [ "Grappa::CallbackMetric< T >", "class_grappa_1_1_callback_metric.html", "class_grappa_1_1_callback_metric" ],
    [ "Grappa::GlobalHashMap< K, V >::Cell", "struct_grappa_1_1_global_hash_map_1_1_cell.html", "struct_grappa_1_1_global_hash_map_1_1_cell" ],
    [ "Grappa::GlobalHashSet< K >::Cell", "struct_grappa_1_1_global_hash_set_1_1_cell.html", "struct_grappa_1_1_global_hash_set_1_1_cell" ],
    [ "CmpElement< Id, Cmp >", "class_cmp_element.html", "class_cmp_element" ],
    [ "Communicator", "class_communicator.html", "class_communicator" ],
    [ "CommunicatorContext", "struct_communicator_context.html", "struct_communicator_context" ],
    [ "Grappa::CompletionEvent", "class_grappa_1_1_completion_event.html", "class_grappa_1_1_completion_event" ],
    [ "Grappa::CompletionTarget", "struct_grappa_1_1_completion_target.html", "struct_grappa_1_1_completion_target" ],
    [ "Grappa::ConditionVariable", "class_grappa_1_1_condition_variable.html", "class_grappa_1_1_condition_variable" ],
    [ "Grappa::CountingSemaphore", "class_grappa_1_1_counting_semaphore.html", "class_grappa_1_1_counting_semaphore" ],
    [ "DictOut", "class_dict_out.html", "class_dict_out" ],
    [ "Grappa::Graph< V, E >::Edge", "struct_grappa_1_1_graph_1_1_edge.html", "struct_grappa_1_1_graph_1_1_edge" ],
    [ "Grappa::TupleGraph::Edge", "struct_grappa_1_1_tuple_graph_1_1_edge.html", "struct_grappa_1_1_tuple_graph_1_1_edge" ],
    [ "Grappa::Empty", "struct_grappa_1_1_empty.html", null ],
    [ "Entry", "class_entry.html", "class_entry" ],
    [ "Grappa::GlobalHashMap< K, V >::Entry", "struct_grappa_1_1_global_hash_map_1_1_entry.html", "struct_grappa_1_1_global_hash_map_1_1_entry" ],
    [ "Grappa::GlobalHashSet< K >::Entry", "struct_grappa_1_1_global_hash_set_1_1_entry.html", "struct_grappa_1_1_global_hash_set_1_1_entry" ],
    [ "Allocator::Exception", "class_allocator_1_1_exception.html", null ],
    [ "Grappa::ExternalCountPayloadMessage< T >", "class_grappa_1_1_external_count_payload_message.html", "class_grappa_1_1_external_count_payload_message" ],
    [ "Grappa::delegate::FetchAddCombiner< T, U >", "class_grappa_1_1delegate_1_1_fetch_add_combiner.html", "class_grappa_1_1delegate_1_1_fetch_add_combiner" ],
    [ "Grappa::File", "struct_grappa_1_1_file.html", "struct_grappa_1_1_file" ],
    [ "Grappa::FlatCombiner< T >", "class_grappa_1_1_flat_combiner.html", "class_grappa_1_1_flat_combiner" ],
    [ "Grappa::FullEmpty< T >", "class_grappa_1_1_full_empty.html", "class_grappa_1_1_full_empty" ],
    [ "function_traits< T >", "structfunction__traits.html", null ],
    [ "function_traits< ReturnType(ClassType::*)(Args...) const  >", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4.html", "structfunction__traits_3_01_return_type_07_class_type_1_1_5_08_07_args_8_8_8_08_01const_01_01_4" ],
    [ "Functor", "struct_functor.html", "struct_functor" ],
    [ "GlobalAddress< T >", "class_global_address.html", "class_global_address" ],
    [ "GlobalAllocator", "class_global_allocator.html", "class_global_allocator" ],
    [ "Grappa::GlobalBag< T >", "class_grappa_1_1_global_bag.html", "class_grappa_1_1_global_bag" ],
    [ "Grappa::GlobalCompletionEvent", "class_grappa_1_1_global_completion_event.html", "class_grappa_1_1_global_completion_event" ],
    [ "Grappa::GlobalCounter", "class_grappa_1_1_global_counter.html", "class_grappa_1_1_global_counter" ],
    [ "Grappa::GlobalHashMap< K, V >", "class_grappa_1_1_global_hash_map.html", "class_grappa_1_1_global_hash_map" ],
    [ "Grappa::GlobalHashSet< K >", "class_grappa_1_1_global_hash_set.html", "class_grappa_1_1_global_hash_set" ],
    [ "GlobalMemory", "class_global_memory.html", "class_global_memory" ],
    [ "GlobalMemoryChunk", "class_global_memory_chunk.html", "class_global_memory_chunk" ],
    [ "Grappa::Metrics::GlobalQueueMetrics", "class_grappa_1_1_metrics_1_1_global_queue_metrics.html", "class_grappa_1_1_metrics_1_1_global_queue_metrics" ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >", "class_grappa_1_1_global_vector.html", "class_grappa_1_1_global_vector" ],
    [ "Grappa::Graph< V, E >", "struct_grappa_1_1_graph.html", "struct_grappa_1_1_graph" ],
    [ "Grappa::HistogramMetric", "class_grappa_1_1_histogram_metric.html", "class_grappa_1_1_histogram_metric" ],
    [ "IAMetrics", "class_i_a_metrics.html", "class_i_a_metrics" ],
    [ "Incoherent< T >", "struct_incoherent.html", "struct_incoherent" ],
    [ "IncoherentAcquirer< T >", "class_incoherent_acquirer.html", "class_incoherent_acquirer" ],
    [ "IncoherentReleaser< T >", "class_incoherent_releaser.html", "class_incoherent_releaser" ],
    [ "Int32Edge", "struct_int32_edge.html", "struct_int32_edge" ],
    [ "Grappa::IODescriptor", "struct_grappa_1_1_i_o_descriptor.html", "struct_grappa_1_1_i_o_descriptor" ],
    [ "IRMetrics", "class_i_r_metrics.html", "class_i_r_metrics" ],
    [ "SmallLocalSet< T, SmallSize >::iterator", "struct_small_local_set_1_1iterator.html", "struct_small_local_set_1_1iterator" ],
    [ "LocalIterator< T >", "struct_local_iterator.html", "struct_local_iterator" ],
    [ "LRQueue", "class_l_r_queue.html", "class_l_r_queue" ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Master", "struct_grappa_1_1_global_vector_1_1_master.html", "struct_grappa_1_1_global_vector_1_1_master" ],
    [ "Grappa::GlobalCounter::Master", "struct_grappa_1_1_global_counter_1_1_master.html", "struct_grappa_1_1_global_counter_1_1_master" ],
    [ "Grappa::MaxMetric< T >", "class_grappa_1_1_max_metric.html", "class_grappa_1_1_max_metric" ],
    [ "Grappa::Message< T >", "class_grappa_1_1_message.html", "class_grappa_1_1_message" ],
    [ "Grappa::MessagePool", "class_grappa_1_1_message_pool.html", "class_grappa_1_1_message_pool" ],
    [ "Grappa::MessagePoolStatic< Bytes >", "class_grappa_1_1_message_pool_static.html", "class_grappa_1_1_message_pool_static" ],
    [ "Grappa::Mutex", "class_grappa_1_1_mutex.html", "class_grappa_1_1_mutex" ],
    [ "NullAcquirer< T >", "class_null_acquirer.html", "class_null_acquirer" ],
    [ "NullReleaser< T >", "class_null_releaser.html", "class_null_releaser" ],
    [ "Grappa::PayloadMessage< T >", "class_grappa_1_1_payload_message.html", "class_grappa_1_1_payload_message" ],
    [ "Grappa::PoolAllocator< Base >", "class_grappa_1_1_pool_allocator.html", "class_grappa_1_1_pool_allocator" ],
    [ "Grappa::PoolAllocatorInternal< Bytes, Base >", "class_grappa_1_1_pool_allocator_internal.html", "class_grappa_1_1_pool_allocator_internal" ],
    [ "Grappa::PrefetchingThreadQueue", "class_grappa_1_1_prefetching_thread_queue.html", "class_grappa_1_1_prefetching_thread_queue" ],
    [ "Grappa::delegate::Promise< R >", "class_grappa_1_1delegate_1_1_promise.html", "class_grappa_1_1delegate_1_1_promise" ],
    [ "Grappa::GlobalCounter::Proxy", "struct_grappa_1_1_global_counter_1_1_proxy.html", "struct_grappa_1_1_global_counter_1_1_proxy" ],
    [ "Grappa::GlobalHashSet< K >::Proxy", "struct_grappa_1_1_global_hash_set_1_1_proxy.html", "struct_grappa_1_1_global_hash_set_1_1_proxy" ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Proxy", "struct_grappa_1_1_global_vector_1_1_proxy.html", "struct_grappa_1_1_global_vector_1_1_proxy" ],
    [ "Grappa::GlobalHashMap< K, V >::Proxy", "struct_grappa_1_1_global_hash_map_1_1_proxy.html", "struct_grappa_1_1_global_hash_map_1_1_proxy" ],
    [ "PushBuffer< T, BUFSIZE, NBUFS >", "struct_push_buffer.html", "struct_push_buffer" ],
    [ "Grappa::GlobalVector< T, BUFFER_CAPACITY >::Range", "struct_grappa_1_1_global_vector_1_1_range.html", "struct_grappa_1_1_global_vector_1_1_range" ],
    [ "Range< T >", "struct_range.html", "struct_range" ],
    [ "Reducer< T, R >", "class_reducer.html", null ],
    [ "Reducer< T, ReducerType::Add >", "class_reducer_3_01_t_00_01_reducer_type_1_1_add_01_4.html", "class_reducer_3_01_t_00_01_reducer_type_1_1_add_01_4" ],
    [ "Reducer< T, ReducerType::And >", "class_reducer_3_01_t_00_01_reducer_type_1_1_and_01_4.html", "class_reducer_3_01_t_00_01_reducer_type_1_1_and_01_4" ],
    [ "Reducer< T, ReducerType::Max >", "class_reducer_3_01_t_00_01_reducer_type_1_1_max_01_4.html", "class_reducer_3_01_t_00_01_reducer_type_1_1_max_01_4" ],
    [ "Reducer< T, ReducerType::Min >", "class_reducer_3_01_t_00_01_reducer_type_1_1_min_01_4.html", "class_reducer_3_01_t_00_01_reducer_type_1_1_min_01_4" ],
    [ "Reducer< T, ReducerType::Or >", "class_reducer_3_01_t_00_01_reducer_type_1_1_or_01_4.html", "class_reducer_3_01_t_00_01_reducer_type_1_1_or_01_4" ],
    [ "ReducerImpl< T, ReduceOp >", "class_reducer_impl.html", "class_reducer_impl" ],
    [ "remote_task_spawn_args< A0, A1, A2 >", "structremote__task__spawn__args.html", "structremote__task__spawn__args" ],
    [ "IncoherentAcquirer< T >::RequestArgs", "struct_incoherent_acquirer_1_1_request_args.html", "struct_incoherent_acquirer_1_1_request_args" ],
    [ "IncoherentReleaser< T >::RequestArgs", "struct_incoherent_releaser_1_1_request_args.html", "struct_incoherent_releaser_1_1_request_args" ],
    [ "Grappa::GlobalHashMap< K, V >::ResultEntry", "struct_grappa_1_1_global_hash_map_1_1_result_entry.html", "struct_grappa_1_1_global_hash_map_1_1_result_entry" ],
    [ "Grappa::GlobalHashSet< K >::ResultEntry", "struct_grappa_1_1_global_hash_set_1_1_result_entry.html", "struct_grappa_1_1_global_hash_set_1_1_result_entry" ],
    [ "Grappa::ReuseMessage< T >", "class_grappa_1_1_reuse_message.html", "class_grappa_1_1_reuse_message" ],
    [ "Grappa::ReuseMessageList< T >", "class_grappa_1_1_reuse_message_list.html", "class_grappa_1_1_reuse_message_list" ],
    [ "RunningStandardDeviation", "class_running_standard_deviation.html", "class_running_standard_deviation" ],
    [ "Grappa::Scheduler", "class_grappa_1_1_scheduler.html", "class_grappa_1_1_scheduler" ],
    [ "SixteenBytes", "struct_sixteen_bytes.html", "struct_sixteen_bytes" ],
    [ "SmallLocalSet< T, SmallSize >", "class_small_local_set.html", "class_small_local_set" ],
    [ "StateTimer", "class_state_timer.html", "class_state_timer" ],
    [ "Grappa::StringMetric", "class_grappa_1_1_string_metric.html", "class_grappa_1_1_string_metric" ],
    [ "Grappa::SummarizingMetric< T >", "class_grappa_1_1_summarizing_metric.html", "class_grappa_1_1_summarizing_metric" ],
    [ "Grappa::SuspendedDelegate", "class_grappa_1_1_suspended_delegate.html", "class_grappa_1_1_suspended_delegate" ],
    [ "Grappa::SuspendedDelegateQueue", "class_grappa_1_1_suspended_delegate_queue.html", "class_grappa_1_1_suspended_delegate_queue" ],
    [ "Grappa::ThreadQueue", "class_grappa_1_1_thread_queue.html", "class_grappa_1_1_thread_queue" ],
    [ "TotalMetric", "class_total_metric.html", "class_total_metric" ],
    [ "Grappa::TupleGraph", "class_grappa_1_1_tuple_graph.html", "class_grappa_1_1_tuple_graph" ],
    [ "Grappa::Worker", "class_grappa_1_1_worker.html", "class_grappa_1_1_worker" ]
];